name: gh-pages

on:
    push:
        branches:
            - master

permissions:
  contents: write

jobs:
  doc_build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.12"]

    env:
      PYTHON_VERSION: ${{ matrix.python-version }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - uses: ./.github/actions/setup_optimizers_linux
        with:
          GUROBI_WLS: ${{ secrets.GUROBI_WLS }}
          COPT_CLIENT_INI: ${{ secrets.COPT_CLIENT_INI }}
          MOSEK_LICENSE: ${{ secrets.MOSEK_LICENSE }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHECK_LICENSE: false

      - name: Build
        run: |
          python -m pip list
          python -m pip install nanobind scikit-build-core[pyproject] typing_extensions
          python -m pip install --no-build-isolation -v .
          python -c "import pyoptinterface as poi; print(dir(poi))"

      - name: Build documentation
        run: |
          pip install -r docs/requirements.txt
          cd docs
          make html
          cd ..

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/build/html
