name: macos-build

on:
    pull_request:
    push:
        branches:
            - master

jobs:

  macos_build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: [macos-14-large, macos-14]
        # python-version: ["3.9", "3.10", "3.11", "3.12"]
        python-version: ["3.11", "3.12"]

    env:
      PYTHON_VERSION: ${{ matrix.python-version }}
      MACOSX_DEPLOYMENT_TARGET: 10.14

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - uses: ./.github/actions/setup_optimizers_macos
        with:
          GUROBI_WLS: ${{ secrets.GUROBI_WLS }}
          COPT_CLIENT_INI: ${{ secrets.COPT_CLIENT_INI }}
          MOSEK_LICENSE: ${{ secrets.MOSEK_LICENSE }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHECK_LICENSE: false
          ARCH: ${{ runner.arch }}

      - name: Install python deps
        run: |
          python -m pip install .[test]

      - name: Build
        run: |
          python -m pip list
          python -m pip install nanobind scikit-build-core[pyproject]
          python -m pip install --no-build-isolation -v .
          python -c "import pyoptinterface as poi; print(dir(poi))"
          python -m pip wheel -w dist --no-build-isolation .

      - name: Test
        run: |
          python -m pytest tests -k "highs or ipopt" -v

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pyoptinterface-wheel-${{ runner.os }}-${{ runner.arch }}-${{ matrix.python-version }}
          path: dist/
